service: planet-express-orders
frameworkVersion: '2'


provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-2
  apiGateway:
    apiKeys:
      - planet-express-order-demo
  environment:
    PLNT_EXPRESS_TBL: ${self:custom.table_name}
    
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:UpdateItem
          Resource:
            - !Sub "${PlanetExpressDB.Arn}"
            - !Sub "${PlanetExpressDB.Arn}/index/*"

            
package:
  patterns:
    - "!**/**"
    - "src/**"

functions:
  HttpCreateCustomer:
    handler: src.handlers.http_create_customer
    events:
      - http:
          path: v1/customer
          method: post
          private: true

  HttpCustomerAddress:
    handler: src.handlers.http_add_address_to_customer
    events:
      - http:
          path: v1/customer/{username}/address
          method: post
          private: true
          request:
            parameters:
              paths:
                username: true

  HttpCreateOrder:
    handler: src.handlers.http_create_order
    events:
      - http:
          path: v1/order
          method: post
          private: true

  HttpGetOrder:
    handler: src.handlers.http_get_domain_order
    events:
      - http:
          path: v1/order/{order_id}
          method: get
          private: true
          request:
            parameters:
              paths:
                order_id: true

  HttpOrderAddLineItem:
    handler: src.handlers.http_add_line_item
    events:
      - http:
          path: v1/order/{order_id}/line_item
          method: post
          private: true
          request:
            parameters:
              paths:
                order_id: true

custom:
  table_name: planet_express_orders
  pythonRequirements:
    usePipenv: true
    dockerizePip: non-linux
    dockerImage: lambci/lambda:build-python3.8
    dockerSsh: true

resources:
  Resources:
    PlanetExpressDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.table_name}
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: 'sk_pk_index'
            Projection:
              ProjectionType: ALL
            KeySchema:
              - AttributeName: sk
                KeyType: HASH
              - AttributeName: pk
                KeyType: RANGE
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1


plugins:
  - serverless-python-requirements
